### ISSUE TITLE
The “Room” page is not displayed properly, because the characters limit of some fields is too long.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#10]
Description:
 When the user fill out some fields with the maximum character limit in the “Room” page, the page is not displayed properly.

-Env:
Using the Hotel_Info Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_info site.
2. On the site bar, locate the “Pages” section.
3. Click on the edit button of the “Rooms & Tariff” Page.
4. Add a new room.
5. Field the room with the next information.
 	Component ID: luxury-room
	Internal Name: Luxury Room
	Name: Luxury Room
	Short Description: Fill out the field with the maximum character limit.
Long Description: Fill out the field with the maximum character limit.
 	Size Label:  Fill out the field with the maximum character limit.
	Size:  Fill out the field with the maximum character limit.
	Price Label:  Fill out the field with the maximum character limit.
	Price:  Fill out the field with the maximum character limit.
Amenities Label:  Fill out the field with the maximum character limit.
6. Click on the Save and Close button.
7. Review the page preview
 
CURRENT RESULT: 
==================== 
The “Room” page is not displayed properly.
https://www.screencast.com/t/Wu6Gb8sBgu4H 
 
EXPECTED RESULT: 
==================== 
The “Room” page should be displayed properly, character limit should be shorter or the text containers should be resizable according to the amount of characters added.

Note.
*Reduce the Long Description character limit to at about 7000 characters, so page is not too long.
*Resize the character container or reduce the character limit of:

- Size Label
- Size
- Price Label
- Price

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Issue verified and closed as fixed, build a115998
