### ISSUE TITLE
The “Amenities” label in the rooms component editor is misspelled.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#11]
Description: 
The “Amenities” label in the rooms component editor is misspelled.  
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Rooms & Tariff“  page.
4. On the rooms list, select one room and click on the edit button
5. Review the content section labels.
 
 
CURRENT RESULT: 
==================== 
The label for “Amenities” is misspelled, it is written as (Amenitites).
https://screencast.com/t/xXxeRosc9IK 
 
EXPECTED RESULT: 
==================== 
The label should not be misspelled.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Issue verified and closed as fixed, build a115998
