### ISSUE TITLE
The application does not display the “Packages” page properly arranged when the "short description" has different amount of characters.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#12]
Description:
When the “short description” of some “packages” is full of characters, the “Rooms & Tariff” site page does not arrange the packages page properly.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Rooms & Tariff“  page.
4. On the rooms list, add 4 rooms with the next properties.
     Package A: Fill all the fields and the “short Description” with the maximum characters limit (300).
     Package B: Fill all the fields and the “short Description” with 100 characters.
     Package C: Fill all the fields and the “short Description” with 20 characters.
     Package D: Fill all the fields and the “short Description” with 150 characters.
     Package E: Fill all the fields and the “short Description” with 150 characters.
5. Click on the Save and Close Button.
6. Go to the page preview of the “Packages” page.
 
 
CURRENT RESULT: 
==================== 
The application displays all the configured “Packages” but they are not arranged properly.
https://www.screencast.com/t/49lYtYRIWQn  
 
EXPECTED RESULT: 
==================== 
The application should display all the configured packages properly arranged.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed.
