### ISSUE TITLE
The “Packages” page is not displayed properly, because the characters limit of some fields is too long.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#13]
Description: 
When the user fill out some fields with the maximum character limit in the “Packages” page, the page is not displayed properly.
 
-Env:
Using the Hotel_Info Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_info site.
2. On the site bar, locate the “Pages” section.
3. Click on the edit button of the “Packages” Page.
4. Add a new Package.
5. Field the room with the next information.
 	Component ID: package-a
	Internal Name: Package A
	Name: Package A
	Short Description: Fill out the field with the maximum character limit.
Long Description: Fill out the field with the maximum character limit.
 	Price Label:  Fill out the field with the maximum character limit.
	Price:  Fill out the field with the maximum character limit.
6. Click on the Save and Close button.
7. Review the page preview
 
CURRENT RESULT: 
==================== 
The “Package” page is not displayed properly.
https://www.screencast.com/t/2dfD0Wiq9W1P 
 
EXPECTED RESULT: 
==================== 
The “Packages” page should be displayed properly, character limit should be shorter or the text containers should be resizable according to the amount of characters added.
 
*Resize the Short Description to at about 300 characters, so page is not too long.
*Resize the Long Description to at about 7000 characters, so page is not too long.
* Resize the character container or reduce the character limit of:
Price Label: 
Price:

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Issue verified and closed as fixed, build a115998
