### ISSUE TITLE
The text of the “Main RTE” of the Home Page is not displayed when the text exceeds 600 characters.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#14]
Description:
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
Mobile: 
Firefox:53.0.2
Google Chrome: 58.0.3029.83

 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Home“  page.
4. Fill out the Main RTE with a text that exceeds 600 characters 
5. Click on the Save and Close Button. 
6. Review the preview of the home page.
 
 
CURRENT RESULT: 
==================== 
The text of the “Main RTE” of the Home Page is not displayed when the text exceeds 600 characters.
https://screencast.com/t/3nXL2FgEghXD
*Note
In Mobile browsers the text is being cut by the secondary RTE.
https://www.screencast.com/t/kPBEIKgAs 
 
EXPECTED RESULT: 
==================== 
All the text off the “Main RTE” should be displayed or the “RTE” should have maximum character limit.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Issue verified and closed as fixed, build a115998.
