### ISSUE TITLE
The “Carrousel” photos are not displayed properly, the photos are displayed in different sizes.   

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#15]
Description: 
The “Carrousel” photos are not displayed properly, the photos are displayed in different sizes. 
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
*Same Steps for the Room Carrousel and for the Packages Carrousel.
 
Room photos carrousel Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Rooms & Tariff“  page.
4. On the rooms list, select one room and click on the edit button
5. Go to the Photos section.
6. Add 4 photos of different sizes. 
7. Click on the Save and Close Button.
8. Go to the page preview of the room.
 
Packages photos carrousel Steps
1. Open the Crafter studio with the Hotel_Info site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Packages“  page.
4. On the packages list, select one package and click on the edit button
5. Go to the Photos section.
6. Add 4 photos of different sizes. 
7. Click on the Save and Close Button.
8. Go to the page preview of the package.
 
CURRENT RESULT: 
==================== 
The Carrousel with the photos is displayed with photos with different sizes. 
 https://www.screencast.com/t/SNaMsmq6u 

EXPECTED RESULT: 
==================== 
The Carrousel with the photos should resize all the added photos so all the photos have the same size and the carrousel is displayed properly.

**Comment by LorenzoRodriguezRivetlogic** [comment]
fixed

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build db94348.
