### ISSUE TITLE
 The Quick links should be in the same order as they are in the Header tabs.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#16]
Description: 
The Quick links should be in the same order as they are in the Header tabs, also the “Home” quick link is missing.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. Review the “Header” links.
3. Review the footer “Quick Links” 
 
CURRENT RESULT: 
==================== 
The “Quick links” in the footer are not in the same order than the links located in the header, also the home link is missing in the footer.
https://www.screencast.com/t/JPC9p8rewq5s 
 
EXPECTED RESULT: 
==================== 
The “Quick links” in the footer should be in the same order than the links located in the header, also the home link should be in the footer.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Issue verified and closed as fixed, build a115998
