### ISSUE TITLE
The "Home" background video is not displayed in mobile browsers. 

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#17]
Description:  
When the user mobile browsers the background video is not displayed.
 
-Env:
Crafter Hotel_Info Blueprint
Iphone 7 IOS 10.3 Safari
Android 7.1
Google Chrome 55.0.2883.79
Firefox 54.0
 
Also happens in:
Device: MacBook Pro 
Safari Version 8.0.5 (10600.5.17)

REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. Go to the “Home” section.
3. Review the section.
 
CURRENT RESULT: 
==================== 
The application is not displaying the background video of the “Home” section in mobile browsers.
 
EXPECTED RESULT: 
==================== 
The application should display the background video of the “Home” section in mobile browsers.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Known issue as specified in the readme file

**Comment by juacamar** [comment]
Bug fixed.
