### ISSUE TITLE
The applications needs that the user click twice the “Social Media” icons to open/redirect to the page in apple devices.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#25]
Description: 
 The applications needs that the user click twice the “Social Media” icons to open/redirect to the page in apple devices.

-Env:
Crafter Hotel Blueprint
Iphone 7 IOS 10.3 
Safari 
Google Chrome Version 55.0.2883.79
Firefox 7.5(3349)

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. Go to the footer.
3.Click on the social media icons.

CURRENT RESULT: 
==================== 
The user needs to click twice the “Social Media” icons to open/redirect to the page in apple devices.
https://www.screencast.com/t/NFDTbudQ3K 

EXPECTED RESULT: 
==================== 
The user should only user need to click one time the “Social Media” icons to open/redirect to the page in apple devices.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build a18e1b1.
