### ISSUE TITLE
The application is displaying an error when the room has configured only 1 “Amenities”.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#3]
Description: 
When the user only configured 1 “amenities” to a room an error message is displayed.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Rooms & Tariff“  page.
4. On the rooms list, select one room and click on the edit button
5. Delete or add new amenities to the room, so the room only contains 1 amenities.
5. Click on the Save and Close Button.
6. Go to the page preview of the room.
 
 
CURRENT RESULT: 
==================== 
The application displays an error message when the room page has only 1 amenities configured.
https://www.screencast.com/t/hJw3UICt 
 
EXPECTED RESULT: 
==================== 
The application should not display any error message when there is only 1 amenities configured for the room.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed, build a115998.
