### ISSUE TITLE
 The application is redirecting to a non existing page when the user clicks the site logo.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#4]
Description: 
When the user click the site logo, it is redirecting to a non existing page.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. In the preview of the site click on the site logo.
 
CURRENT RESULT: 
==================== 
The application redirects to a non existing page.
https://www.screencast.com/t/hVs3PqBdf
 
EXPECTED RESULT: 
==================== 
The application should redirects to a valid site, or the logo should not be a link to another page.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed, build a115998.
