### ISSUE TITLE
The site logo is not displayed properly when is bigger than the header.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#5]
Description: 
When the user select a site logo bigger than the header size, the site logo is not displayed properly.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. In the site bar go to the “Pages” section.
3. Click on the edit button of the “Section Defaults“ section.
4. In the “Header and Footer” section, select the default header and click on the edit button.
5. Replace the site logo, with a bigger image.
6. Click on the Save and Close Button.
7. Review the logo in the preview of the site.
 
CURRENT RESULT: 
==================== 
The site logo is not displayed properly.
https://www.screencast.com/t/HT9ql6twO
 
EXPECTED RESULT: 
==================== 
The application should resize the logo image and displayed properly.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build db94348.
