### ISSUE TITLE
The application is displaying an error when the room gallery contains only 1 photo.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#6]
Description: 
When the room gallery contains only 1 photo the application is displaying an error.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Rooms & Tariff“  page.
4. On the rooms list, select one room and click on the edit button
5.Go to the Photos section.
5. Delete or add 1 new photo to the room, so the room only contains 1 photo.
5. Click on the Save and Close Button.
6. Go to the page preview of the room.
 
 
CURRENT RESULT: 
==================== 
The application displays an error when the room gallery has only 1 photo.
https://www.screencast.com/t/qPsVsO2Mm 
 
EXPECTED RESULT: 
==================== 
The application should not display any error message when there is only 1 photo for the room.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Issue verified and closed as fixed, build a115998
