### ISSUE TITLE
The application does not display the rooms properly arranged when the "short description" has different amount of characters.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#7]
Description:
When the “short description” of some rooms is full of characters, the “Rooms & Tariff” site page does not arrange the rooms properly.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Rooms & Tariff“  page.
4. On the rooms list, add 4 rooms with the next properties.
     Room A: Fill all the fields and the “short Description” with the maximum characters limit (300).
     Room B: Fill all the fields and the “short Description” with 100 characters.
     Room C: Fill all the fields and the “short Description” with 20 characters.
     Room D: Fill all the fields and the “short Description” with 150 characters.
     Room E: Fill all the fields and the “short Description” with 150 characters.
5. Click on the Save and Close Button.
6. Go to the page preview of the “Rooms & Tariff” page.
 
 
CURRENT RESULT: 
==================== 
The application displays all the configured rooms but they are not arranged properly.
https://www.screencast.com/t/i3sCFlxlGTU 
 
EXPECTED RESULT: 
==================== 
The application should display all the configured rooms properly arranged.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed.
