### ISSUE TITLE
The application is displaying an error when the “Packages” gallery contains only 1 photo.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#8]
Description: 
When the “Packages” gallery contains only 1 photo the application is displaying an error.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Packages“  page.
4. On the “Packages” list, select one “Packages” and click on the edit button
5.Go to the Photos section.
6. Delete or add 1 new photo to the “Package selected”, so the Package only contains 1 photo.
7. Click on the Save and Close Button.
8. Go to the page preview of the Package.
 

CURRENT RESULT: 
==================== 
The application displays an error when the “Package selected” gallery has only 1 photo.
https://screencast.com/t/Ex9S6OTjVj
 
EXPECTED RESULT: 
==================== 
The application should not display any error message when there is only 1 photo for the Package.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Issue verified and closed as fixed, build a115998
