### ISSUE TITLE
 The application is displaying an error when the a “Package” have only 1 included service.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-hotelinfo#9]
Description: 
When the “Packages” gallery only contains 1 “Included service” the application is displaying an error.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Hotel_Info site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Packages“  page.
4. On the “Packages” list, select one “Packages” and click on the edit button
5.Go to the Content section.
6. Delete or add 1 new “Included services” to the “Package selected”, so the Package only contains 1 included service.
7. Click on the Save and Close Button.
8. Go to the page preview of the Package.
 
CURRENT RESULT: 
==================== 
The application displays an error when the a “Package” has only 1 “Included service”.
https://www.screencast.com/t/kpjuwr4c26ls 
 
EXPECTED RESULT: 
==================== 
The application should not display any error message when the  a “Package” has only 1 “Included service”.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Issue verified and closed as fixed, build a115998.
